project_name: elemental-operator
builds:
  - main: ./cmd/operator
    binary: elemental-operator
    id: elemental-operator
    env:
      - CGO_ENABLED=0
    ldflags:
      - -w -s
      - -X github.com/rancher/elemental-operator/pkg/version.Version={{.Tag}}
      - -X github.com/rancher/elemental-operator/pkg/version.Commit={{.Commit}}
      - -X github.com/rancher/elemental-operator/pkg/version.CommitDate={{.CommitDate}}
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
  - main: ./cmd/register
    binary: elemental-register
    id: elemental-register
    env:
      - CGO_ENABLED=1
    ldflags:
      - -w -s
      - -X github.com/rancher/elemental-operator/pkg/version.Version={{.Tag}}
      - -X github.com/rancher/elemental-operator/pkg/version.Commit={{.Commit}}
      - -X github.com/rancher/elemental-operator/pkg/version.CommitDate={{.CommitDate}}
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    overrides: # Disable CGO on arm platforms, means that we don't support emulated TPM under arm
      - goarch: arm
        goos: linux
        goarm: 6
        env:
          - CGO_ENABLED=0
      - goarch: arm
        goos: linux
        goarm: 7
        env:
          - CGO_ENABLED=0
      - goarch: arm64
        goos: linux
        env:
          - CGO_ENABLED=0
  - main: ./cmd/support
    binary: elemental-support
    id: elemental-support
    env:
      - CGO_ENABLED=0
    ldflags:
      - -w -s
      - -X github.com/rancher/elemental-operator/pkg/version.Version={{.Tag}}
      - -X github.com/rancher/elemental-operator/pkg/version.Commit={{.Commit}}
      - -X github.com/rancher/elemental-operator/pkg/version.CommitDate={{.CommitDate}}
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Tag }}-source'
archives:
  # Default template uses underscores instead of -
  - name_template: "{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: '{{ .ProjectName }}-{{ .Tag }}-checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge pull request'
