kind: APIService
apiVersion: management.cattle.io/v3
metadata:
  name: elemental-operator
spec:
  secretName: elemental-operator
  secretNamespace: {{ .Release.Namespace }}
  pathPrefixes:
  - /elemental/
