apiVersion: apps/v1
kind: Deployment
metadata:
  name: elemental-operator
spec:
  selector:
    matchLabels:
      app: elemental-operator
  template:
    metadata:
      labels:
        app: elemental-operator
    spec:
      containers:
      - env:
        - name: NAMESPACE
          value: {{ .Release.Namespace }}
        - name: SYNC_INTERVAL
          value: {{.Values.sync_interval}}
        - name: OPERATOR_IMAGE
          value: {{ template "system_default_registry" . }}{{ .Values.image.repository }}:{{ .Values.image.tag }}
        {{- if .Values.proxy }}
        - name: HTTP_PROXY
          value: {{ .Values.proxy }}
        - name: HTTPS_PROXY
          value: {{ .Values.proxy }}
        - name: NO_PROXY
          value: {{ .Values.noProxy }}
        {{- end }}
        {{- if .Values.hostbin }}
        image: '{{ template "system_default_registry" . }}{{ .Values.image.empty }}'
        volumeMounts:
          - mountPath: /usr/sbin/ros-operator
            name: sbin
        {{- else }}
        image: '{{ template "system_default_registry" . }}{{ .Values.image.repository }}:{{ .Values.image.tag }}'
        {{- end }}
        name: elemental-operator
        imagePullPolicy: "{{ .Values.image.imagePullPolicy }}"
        command:
        - /usr/sbin/elemental-operator
        args:
        - start-operator
      {{- if .Values.hostbin }}
      volumes:
        - name: sbin
          hostPath:
            type: File
            path: /usr/sbin/elemental-operator
      {{- end }}
      serviceAccountName: elemental-operator
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
