apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elemental-operator
rules:
- apiGroups:
  - ""
  resources:
  - 'events'
  verbs:
  - 'patch'
  - 'create'
- apiGroups:
  - ""
  resources:
  - 'secrets'
  verbs:
  - 'get'
  - 'watch'
  - 'list'
- apiGroups:
  - ""
  resources:
  - 'pods'
  verbs:
  - 'get'
  - 'create'
  - 'delete'
  - 'list'
- apiGroups:
  - ""
  resources:
  - 'pods/log'
  verbs:
  - 'get'
- apiGroups:
  - elemental.cattle.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - fleet.cattle.io
  resources:
  - 'bundles'
  verbs:
  - '*'
- apiGroups:
  - provisioning.cattle.io
  resources:
  - 'clusters'
  verbs:
  - 'get'
  - 'watch'
  - 'list'
- apiGroups:
  - management.cattle.io
  resources:
  - 'clusterregistrationtokens'
  verbs:
  - '*'
- apiGroups:
  - management.cattle.io
  resources:
  - 'settings'
  verbs:
  - 'get'
  - 'watch'
  - 'list'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - 'list'
  - 'get'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elemental-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: elemental-operator
subjects:
- kind: ServiceAccount
  name: elemental-operator
  namespace: {{.Release.Namespace}}
