name: Build and publish chart
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - 'v*'
jobs:
  chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build chart for CI
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          make chart
      - name: Build chart for release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          REPO=quay.io/costoolkit/rancheros-operator TAG=${GITHUB_REF##*/} make chart
      - name: Publish chart to release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_COMPRESS: tgz
          GHR_PATH: build/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Helm
        if: startsWith(github.ref, 'refs/tags/')
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1
      - name: Build and push index
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git checkout gh-pages
          rm index.yaml
          helm repo index --url https://rancher-sandbox.github.io/rancheros-operator .
          git add index.yaml build/ -f
          git commit -m "Updating helm repo to main commit ${{ github.sha }}"
          git push --set-upstream origin gh-pages
          
