name: e2e tests
on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  group: e2e-tests=full-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
jobs:
  push-docker:
    runs-on: ubuntu-latest
    outputs:
      chart_name: ${{ steps.chart.outputs.chart_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Export tag
        id: export_tag
        run: |
          TAG=`git describe --abbrev=0 --tags 2>/dev/null || echo "v0.0.0"`
          echo "::set-output name=ros_tag::$TAG"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            quay.io/costoolkit/rancheros-operator-ci
          tags: |
            type=sha,format=short,prefix=${{ steps.export_tag.outputs.ros_tag }}-
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Make chart
        run: make chart
      - name: Set chart output
        id: chart
        run: |
          CHART=$(basename `find . -type f  -name "rancheros-operator*.tgz" -print`)
          echo "::set-output name=chart_name::$CHART"
      - name: Upload chart
        uses: actions/upload-artifact@v2
        with:
          name: chart
          path: build/*.tgz
  e2e-tests:
    strategy:
      matrix:
        kubernetes: [ "v1.22.7" ]
    runs-on: ubuntu-latest
    needs: push-docker
    env:
      ROS_CHART: ${{ github.workspace }}/build/${{ needs.push-docker.outputs.chart_name }}
      KUBE_VERSION: ${{ matrix.kubernetes }}
    steps:
      - uses: actions/checkout@v2
      - name: Download chart
        uses: actions/download-artifact@v2
        with:
          name: chart
          path: build
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: Deps
        run: make test_deps
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
          skipClusterCreation: "true"
      - name: e2e tests
        run: make e2e-tests