name: Integration tests
on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  group: integration-tests=full-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
jobs:
  push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push
        run: make build-docker-push
      - name: Make chart
        run: make chart
      - name: Upload chart
        uses: actions/upload-artifact@v2
        with:
          name: chart
          path: build/*.tgz
  tests-vbox:
    runs-on: macos-10.15
    needs: push-docker
    env:
      VAGRANT_CPU: 3
      VAGRANT_MEMORY: 10240
      ROS_CHART: ${{ github.workspace }}/build/rancheros-operator-0.0.0-dev.tgz
    steps:
      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: ${{ runner.os }}-vagrant-
      - uses: actions/checkout@v2
      - name: Download chart
        uses: actions/download-artifact@v2
        with:
          name: chart
          path: build
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: Deps
        run: make test_deps
      - name: Integration tests
        run: make integration-tests